/*
 * ServoDefs.h
 *
 *  Created on: 24 nov. 2016
 *      Author: Md
 */

#ifndef SERVODEFS_H_
#define SERVODEFS_H_


#define SV_BRAS RXID(7)
#define SV_PINCE RXID(22)
#define SV_EPAULE RXID(24)
#define SV_FOURCHE RXID(23)
//valeurs vrais
#define _SV_SOLAIREG RXID(18)
#define _SV_SOLAIRED RXID(20)

//symétrisés
#define SV_SOLAIRED ((COULEUR==COULEUR_DEF) ?_SV_SOLAIRED:_SV_SOLAIREG)
#define SV_SOLAIREG ((COULEUR==COULEUR_DEF) ?_SV_SOLAIREG:_SV_SOLAIRED)

#define EPAULE_BAS 429
#define EPAULE_HAUT 890
#define EPAULE_PRISE_PLANTE 458
#define EPAULE_PRISE_POT 595 //530
#define EPAULE_DEPOT_PLANTE 641  //586
#define EPAULE_RANGE 870
#define EPAULE_TRANSPORT 870


#define BRAS_BAS 282
#define BRAS_HAUT 886
#define BRAS_PRISE_PLANTE 861
#define BRAS_PRISE_POT 733 	//800
#define BRAS_DEPOT_PLANTE 678  //740
#define BRAS_RANGE 892
#define BRAS_TRANSPORT 541

#define PINCE_OUVERTE 349
#define PINCE_FERMEE 570
#define PINCE_POT 498	//515

//positions vraies
#define _SOLG_REPLI_GAUCHE 820
#define _SOLG_DEPLI 520
#define _SOLG_REPLI_DROITE 210

#define _SOLD_REPLI_DROITE 160
#define _SOLD_DEPLI 470
#define _SOLD_REPLI_GAUCHE 780

//positions symétrisés
#define SOLG_REPLI_GAUCHE ((COULEUR==COULEUR_DEF) ?_SOLG_REPLI_GAUCHE:_SOLD_REPLI_DROITE)
#define SOLD_REPLI_DROITE ((COULEUR==COULEUR_DEF) ?_SOLD_REPLI_DROITE:_SOLG_REPLI_GAUCHE)
#define SOLG_DEPLI ((COULEUR==COULEUR_DEF) ?_SOLG_DEPLI:_SOLD_DEPLI)
#define SOLD_DEPLI ((COULEUR==COULEUR_DEF) ?_SOLD_DEPLI:_SOLG_DEPLI)
#define SOLG_REPLI_DROITE ((COULEUR==COULEUR_DEF) ?_SOLG_REPLI_DROITE:_SOLD_REPLI_GAUCHE)
#define SOLD_REPLI_GAUCHE ((COULEUR==COULEUR_DEF) ?_SOLD_REPLI_GAUCHE:_SOLG_REPLI_DROITE)

#endif /* SERVODEFS_H_ */
